# Generated by Django 2.1 on 2018-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreateNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('news_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
