# Generated by Django 2.1 on 2018-09-03 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatenews',
            name='news_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст новости'),
        ),
    ]
