# Generated by Django 2.1 on 2018-09-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180911_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreatenews',
            old_name='news_text',
            new_name='description',
        ),
    ]
